mod device;
mod files;
mod gitrepo;
mod global;
mod music;
mod notepad;
mod output;
mod qr;
mod remote;
mod remote_output;
mod system;
mod weather;
mod wol;

pub use device::DevicePlugin;
pub(crate) use files::{safe_file_path, ALLOWED_FOLDERS};
pub use files::FilesPlugin;
pub use gitrepo::GitRepoPlugin;
pub use global::GlobalPlugin;
pub(crate) use music::{MUSIC_DIR, SUBTITLE_LANG_PRIORITY};
pub use music::MusicPlugin;
pub(crate) use notepad::{DEFAULT_NOTEPAD_FILE, NOTEPAD_DIR};
pub use notepad::NotepadPlugin;
pub use output::OutputPlugin;
pub use qr::QrPlugin;
pub use remote::RemotePlugin;
pub use remote_output::RemoteOutputPlugin;
pub(crate) use system::REPORT_INTERVAL;
pub use system::SystemPlugin;
pub use weather::WeatherPlugin;
pub use wol::WolPlugin;
